### ISSUE TITLE
Waiting for root device /dev/mmcblk0p1

### ISSUE THREAD

**Issue by aep** [boundarydevices/buildroot-external-boundary#1]
https://github.com/boundarydevices/linux-imx6/issues/45#issuecomment-389166518 mentioned that i should be using upstream kernel instead.

How would i do this for the 6max?
Just selecting Kernel->Kernel Version->Latest
with this external will not compile because of:
make[3]: *** No rule to make target 'arch/arm/boot/dts/imx6dl-nitrogen6_vm.dtb'.  Stop.

**Comment by gibsson** [comment]
Which configuration are you using?
Note that, as written in the README, if you use mainline kernel, you need to use nitrogen6x_qt5_gst1_mainline_defconfig which doesn't seem to be your case.

**Comment by aep** [comment]
that's correct, i was using nitrogen6x_qt5_gst1_defconfig, since nitrogen6x_qt5_gst1_mainline_defconfig appears to be for internal nand.

```
[    4.478060] Waiting for root device /dev/mmcblk0p1...
```

i'll try to debug this one then, thanks so far!

**Comment by gibsson** [comment]
Not sure to understand you comment about mainline defconfig for internal nand. We do not have NAND on any of our platforms. This config is, as listed in the README, equivalent to the other nitrogen6x one, just meant for mainline kernel.
As for your issue, you most likely use an outdated U-Boot, please upgrade:
https://boundarydevices.com/wiki/u-boot/
Then make sure to close that thread ;-)
Thanks!

**Comment by aep** [comment]
sorry, what i mean is whatever is /dev/mmcblk0p2
internal flash instead of sdcard
upgrading uboot has no effect. i think this is built into the kernel

**Comment by gibsson** [comment]
Have you upgraded? Can you copy the serial log to pastebin?
root= parameter shouldn't use /dev/xxxx in the first place, that's your issue.
Have a look at the bootscript.

**Comment by aep** [comment]
```
U-Boot 2017.07-28766-ga32ffa6 (Mar 20 2018 - 15:54:06 -0700), Build: jenkins-uboot_v2017.07-82

CPU:   Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: nitrogen6_max
I2C:   ready
DRAM:  3.8 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
SF: Detected sst25vf016b with page size 256 Bytes, erase size 4 KiB, total 2 MiB
*** Warning - bad CRC, using default environment

Display: hdmi:1280x720M@60 (1280x720)
In:    serial
Out:   serial
Err:   serial
Net:   Micrel ksz9021 at 6
FEC [PRIME], usb_ether
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot/boot.scr
4145 bytes read in 7 ms (578.1 KiB/s)
## Executing script at 10008000
** File not found uEnv.txt **
44018 bytes read in 11 ms (3.8 MiB/s)
** Invalid partition 2 **
6446992 bytes read in 311 ms (19.8 MiB/s)
Kernel image @ 0x10800000 [ 0x000000 - 0x625f90 ]
## Flattened Device Tree blob at 13000000
   Booting using the fdt blob at 0x13000000
   reserving fdt memory region: addr=13000000 size=b000
   Using Device Tree in place at 13000000, end 1300dfff

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0                                                                                                                                                                 
[    0.000000] Linux version 4.14.12 (aep@stark) (gcc version 7.2.1 20171011 (Linaro GCC 7.2-2017.11)) #1 SMP Tue May 15 20:19:46 CEST 2018
[    0.000000] CPU: ARMv7 Processor [412fc09a] revision 10 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Boundary Devices i.MX6 Quad Nitrogen6_MAX Board
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 256 MiB at 0xee000000
[    0.000000] random: fast init done
[    0.000000] percpu: Embedded 16 pages/cpu @e4990000 s36072 r8192 d21272 u65536
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 981807
[    0.000000] Kernel command line: console=ttymxc1,115200 vmalloc=400M cma=256M consoleblank=0 root=/dev/mmcblk0p2 rootwait reset_cause=0x1 snd.slots=,snd-soc-imx-hdmi
```


note the  ** Invalid partition 2 **  . there is no partition 2 generated from buildroot. it's all on 1



and yes, i did upgrade to the latest version from the link you gave me ;)

**Comment by aep** [comment]
editing  bootscript-mainline.txt and changing line 104 to:

```
    rfspart=1
```

fixed it for me

**Comment by gibsson** [comment]
Hi,

Yes good point, this is due to a bad configuration on our end:
https://github.com/boundarydevices/buildroot-external-boundary/blob/2018.02.x/configs/nitrogen6x_qt5_gst1_mainline_defconfig#L40

It used to use this bootscript:
https://github.com/boundarydevices/buildroot-external-boundary/blob/2018.02.x/board/boundarydevices/mainline/6x_bootscript.txt

Then you should have root=UUID=XXXX which is preferred. It will be patched, thanks for tracking it down!
