### ISSUE TITLE
mmc index changed

### ISSUE THREAD

**Issue by aep** [boundarydevices/buildroot-external-boundary#3]
currently trying 4.14.12 and the mmc indexes start at 1 instead of 0 so the uboot script fails again.

https://gist.github.com/aep/1a69980fbbaa5cc7bbd02d4fbb9e500a/

i really think this shouldnt use index numbers. they might change randomly

**Comment by gibsson** [comment]
Hi,
For such issue you can switch to using UUID root argument:
https://github.com/boundarydevices/buildroot-external-boundary/blob/2020.08.x/board/boundarydevices/mainline/bootscript-mainline.txt#L110
Regards
