### ISSUE TITLE
[opencl] nitrogen6x_qt5_gst1_defconfig

### ISSUE THREAD

**Issue by RomainNaour** [boundarydevices/buildroot-external-boundary#5]
Hello,

I'm using the defconfig nitrogen6x_qt5_gst1_defconfig on the sabrelite board.
The image has been generated using the 2020.08.x branch.

I'm looking at opencl imx6 support.
Indeed the package imx-gpu-viv provide cl.h and libOpenCl.so (the Buildroot packaging should be updated since it's an libopencl provided).

But testing the example in /usr/share/examples/viv_samples/cl11/UnitTest/clinfo return an error:

`Error # -1001 at line 156 , in file main.cpp`

I tried other examples from [1] without issues.

Do you have any advice ?

[1] https://github.com/boundarydevices/buildroot-external-boundary#using-the-image

Best regards,
Romain

**Comment by RomainNaour** [comment]
The error was due to the missing vendor ICDs Loader file (Vivante.icd) that must be installed in /etc/OpenCL/vendors directory.

See the yocto recipes as example:
https://github.com/Freescale/meta-freescale/blob/master/recipes-graphics/imx-gpu-viv/imx-gpu-viv-6.inc#L216

With this file installed, the clinfo from /usr/share/examples/viv_samples/cl11/UnitTest/clinfo return some informations about the opencl support. (Note, the clinfo from the clinfo package works too).

Best regards,
Romain

**Comment by gibsson** [comment]
Thanks for the update!
